/** Structured Our Menu (home); generated by `node scripts/extract-our-menu.mjs`. */

export type OurMenuCover = {
  alt: string;
  src: string;
  width?: number;
  height?: number;
  sizes?: string;
  dataWId?: string;
};

export type OurMenuPattern = {
  dataWId?: string;
};

export type OurMenuItem = {
  imageAlt: string;
  imageSrc: string;
  imageSizes?: string;
  name: string;
  price: string;
  description: string;
  productHref: string;
  buttonWId?: string;
};

export type OurMenuTab = {
  id: string;
  label: string;
  items: OurMenuItem[];
};

export type OurMenuData = {
  version: number;
  heading: string;
  defaultTabId: string;
  cover: OurMenuCover;
  pattern?: OurMenuPattern;
  tabs: OurMenuTab[];
};
